export const SET_LANGUAGE = 'SET_LANGUAGE'

export const REMOVE_LANGUAGE = 'REMOVE_LANGUAGE'

export const SET_CURRENT_USER = 'SET_CURRENT_USER'

export const REMOVE_CURRENT_USER = 'REMOVE_CURRENT_USER'

export const CHANGE_CURRENT_USER = 'CHANGE_CURRENT_USER'

export const SET_IBM_UNIQUE_ID = 'SET_IBM_UNIQUE_ID'

export const REMOVE_IBM_UNIQUE_ID = 'REMOVE_IBM_UNIQUE_ID'

export const SET_HEADER_TAB = 'SET_HEADER_TAB'

export const REMOVE_HEADER_TAB = 'REMOVE_HEADER_TAB'

export const SET_REGISTER = 'SET_REGISTER'

export const SET_REGISTER_ATTRIBUTES = 'SET_REGISTER_ATTRIBUTES'

export const SET_REGISTER_AUTHORIZATION = 'SET_REGISTER_AUTHORIZATION'

export const SET_REGISTER_ENTITLEMENT = 'SET_REGISTER_ENTITLEMENT'

export const SET_REGISTER_EMAILDOMAINS = 'SET_REGISTER_EMAILDOMAINS'

export const SET_CURRENT_USERLIST = 'SET_CURRENT_USERLIST'

export const REMOVE_CURRENT_USERLIST = 'REMOVE_CURRENT_USERLIST'
